services:
  backend:
    command: npm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"

  ml-service:
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./ml-service/main.py:/app/main.py
      - ./ml-service/models:/app/models
